version: "3.9"
services:
  litellm:
    image: ghcr.io/berriai/litellm:latest
    ports:
      - "4000:4000"
    volumes:
      - ./orchestrator/config/litellm.config.yaml:/app/config.yaml:ro
    environment:
      - LITELLM_CONFIG=/app/config.yaml
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - IMAGE_API_KEY=${IMAGE_API_KEY}
    command: ["--config", "/app/config.yaml"]

  langfuse-db:
    image: postgres:15
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse
    volumes:
      - langfuse_db:/var/lib/postgresql/data

  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    depends_on:
      - langfuse-db
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${LANGFUSE_DATABASE_URL:-postgresql://langfuse:langfuse@langfuse-db:5432/langfuse}
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET:-devsecret}
      - SALT=${LANGFUSE_SALT:-devsalt}

  pw:
    image: mcr.microsoft.com/playwright:v1.48.0-jammy
    tty: true
    shm_size: 2gb
    working_dir: /workspace
    volumes:
      - ./orchestrator/pw-runner:/workspace
      - /workspace/node_modules
    command: ["bash","-lc","npm ci && npx playwright install --with-deps && tail -f /dev/null"]

volumes:
  langfuse_db:
