model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_base: https://api.openai.com/v1
      timeout: 60
      metadata:
        project: glp1-companion
        agent: orchestrator
  - model_name: gemini-flash
    litellm_params:
      model: google/gemini-pro
      api_base: https://generativelanguage.googleapis.com
      timeout: 60
      metadata:
        project: glp1-companion
        agent: researcher
router:
  - model_name: orchestrator-default
    routing_strategy: simple_router
    models:
      - gpt-4o-mini
      - gemini-flash
budget_config:
  total_budget_in_dollars: 50
  per_agent_budget_in_dollars:
    orchestrator: 25
    researcher: 15
    builder: 10
